.PHONY: build build-console run stop clean

BINARY_NAME=go_text.exe

# Сборка в GUI-режиме (без появления окна консоли при запуске)
build:
	go build -o $(BINARY_NAME)

# Сборка и запуск приложения в фоне
run: 
	go run .

